# Generated by Django 4.1.3 on 2023-06-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
    ]
