# Generated by Django 4.1.3 on 2023-06-21 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0002_remove_contact_priority_remove_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='next_reminder',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-weekly', 'Bi-weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Bi-annual', 'Bi-annual'), ('Annual', 'Annual')], max_length=10),
        ),
    ]
