# Generated by Django 4.1.3 on 2023-06-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0003_contact_next_reminder_alter_contact_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
