# Generated by Django 4.1.3 on 2023-06-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0005_auto_20230621_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='position',
            field=models.IntegerField(),
        ),
    ]
